# -*- coding: utf-8 -*-
"""face recogination.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxnAIHFLRzl1JnXWMzzcL8F-vKLQ2SFs
"""

from google.colab import drive
drive.mount('/content/drive')
data=("/content/drive/MyDrive/my/lfw-funneled.tgz")

import tarfile
extract_path = "/content/lfw_dataset"
with tarfile.open(data, "r:gz") as tar:
    tar.extractall(path=extract_path)
print("Extraction Complete!")

import os
os.listdir(extract_path)

dataset_path = "/content/lfw_dataset/lfw_funneled"

os.listdir(dataset_path)[:10]

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

images = []
labels = []
for person in os.listdir(dataset_path):
    person_path = os.path.join(dataset_path, person)
    if os.path.isdir(person_path):
        for image_name in os.listdir(person_path):
            image_path = os.path.join(person_path, image_name)
            img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            if img is None:
                continue
            img = cv2.resize(img, (100,100))
            images.append(img.flatten())
            labels.append(person)

from collections import Counter

counter = Counter(labels)

valid_people = []

for person,count in counter.items():

    if count >= 20:
        valid_people.append(person)

X = []
y = []

for img,label in zip(images,labels):

    if label in valid_people:

        X.append(img)
        y.append(label)

X = np.array(X)
y = np.array(y)

print("\nFiltered Dataset")
print("Images :",X.shape)
print("Classes :",len(np.unique(y)))

plt.figure(figsize=(12,5))

for i in range(5):

    plt.subplot(1,5,i+1)

    plt.imshow(X[i].reshape(100,100),cmap="gray")

    plt.title(y[i],fontsize=8)

    plt.axis("off")

plt.show()

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
print("Train Dataset Shape :", x_train.shape[0])
print("Test Dataset Shape  :", x_test.shape[0])

print(x_train.shape)

scale=StandardScaler()
x_train=scale.fit_transform(x_train)
x_test=scale.transform(x_test)

pca = PCA(
    n_components=0.95,
    whiten=True,
    random_state=42
)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

print("After PCA :", x_train.shape)

knn = KNeighborsClassifier(
       n_neighbors=3,
    weights="distance",
    metric="euclidean"
)
knn.fit(x_train,y_train)

y_pred = knn.predict(x_test)

print("\nAccuracy\n")
print(accuracy_score(y_test, y_pred))
print("\nClassification Report\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix\n")
print(confusion_matrix(y_test, y_pred))

!pip install joblib

import joblib

joblib.dump(knn,"knn_face_model.pkl")
joblib.dump(scale,"scaler.pkl")
joblib.dump(pca,"pca.pkl")
print("\nModel Saved Successfully")

!git config --global user.name "chetan0722"
!git config --global user.email "sakherraj74@gmail.com"

!git config --global user.name
!git config --global user.email

!pwd
!ls

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/app.py
# 
# import streamlit as st
# import cv2
# import joblib
# import numpy as np
# from PIL import Image
# 
# model = joblib.load("knn_face_model.pkl")
# scaler = joblib.load("scaler.pkl")
# pca = joblib.load("pca.pkl")
# 
# st.title("Face Recognition using KNN")
# 
# uploaded_file = st.file_uploader("Upload Image", type=["jpg","png","jpeg"])
# 
# if uploaded_file is not None:
# 
#     image = Image.open(uploaded_file).convert("L")
#     image = np.array(image)
# 
#     st.image(image)
# 
#     image = cv2.resize(image,(100,100))
#     image = image.flatten().reshape(1,-1)
# 
#     image = scaler.transform(image)
#     image = pca.transform(image)
# 
#     prediction = model.predict(image)
# 
#     st.success(prediction[0])